#!/usr/bin/perl -s
##
##
##
## Copyright (c) 1999, Vipul Ved Prakash.  All rights reserved.
## This code is free software; you can redistribute it and/or modify
## it under the same terms as Perl itself.
##
## $Id$


use Crypt::3DES; 

my $des = new Crypt::3DES; 
die "syntax: $0 -e|-d -pass=passphrase datafile\n" unless $pass; 
$data = join'',<>; 
print $des->encrypt3 ( $data, $pass ) if $e; 
print $des->decrypt3 ( $data, $pass ) if $d; 





